name: Validate Conf Structure

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run checker unit tests
        run: python3 ci/test_validate_qcom_conf.py

      - name: Validate repo structure
        run: python3 ci/validate_qcom_conf.py .
