name: Validate Conf Structure

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ci]
    paths-ignore:
      - '.github/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate repo structure
        run: python3 ci/validate_qcom_conf.py .
